.TH HAYALET-SEVGILIM 7 "October 2025" "Hayalet Sevgilim" "User Commands"
.SH NAME
hayalet-sevgilim \- ceza mı bu, çektiğim çile mi?
.SH SYNOPSIS
hayalet-sevgilim [--özle] [--ağla] [--dön]
.SH DESCRIPTION
.PP
Yıllardır tuttuğum nöbet bitmeyecek mi?
Bir küçük kar tanesi gibiyim,
avucunda eriyen dön bebeğim.
.PP
Gözyaşlarını görürsem,
erir kanatlarım,
uçamam rüyalarında yanına.
.PP
Sonsuzluk senle başladı
o küçük dünyamda.
Unutma gittiğinde yarım kaldım.
.SH EXAMPLES
.PP
Çöllerdeyim yanıyorum
.br
Kutuptayım üşüyorum
.br
ceza benim çekiyorum ne olur dön
.br
uzanıyorum tutamıyorum
.br
özlüyorum ağlıyorum
.br
yasak mısın anlamıyorum ne olur dön
.SH OPTIONS
.TP
.B --özle
Sevmesen de beni özledim sesini.
.TP
.B --gitme
Git desem de yine gitmesen.
.TP
.B --haram
Yıllardır çektiğim bu hasret mi, çile mi?
.SH AUTHOR
Hayalet Sevgilim

